---
title: "DRAFT_Cleaning"
output: html_document
date: "2024-12-04"
---

```{r setup, include=FALSE}
library(readr)
library(tidyverse)
library(lubridate)
library(caret)
library(ggfortify)
library(ggformula)
library(DiagrammeR)

dredge_data<-read_csv("DredgeData.csv")
survey_data<-read_csv("SurveyData.csv")
gage_data<-read_csv("UMR_IWW_1999_2021.csv")


gage_data2<- gage_data |>
  group_by(Date)|>
   summarize(across(everything(),~first(na.omit(.)), .names = "{.col}"))|>
  mutate(DATE_START= as_date(dmy(Date)))|>
    arrange(DATE_START)

gage_data2<-gage_data2|>
    mutate(across(c(-Date,-DATE_START),
                ~ ifelse(is.na(.),
                         coalesce((lag(.) + lead(.)) / 2, lag(.), lead(.)),
                         .)))|>
  select(-Date)


survey_Data<- survey_data |>
  filter(SURVEYTYPE == "conditional",
         SURVEY_YEAR >= 1999 & SURVEY_YEAR <= 2022,
          RIVER == "Mississippi_River" | RIVER == "Illinois_Waterway",
         SURVEYJOBIDPK == str_replace_all(SURVEYJOBIDPK, "IL", "IW"),
         !POOL %in% c("LP","CS"))|>
  mutate(VOLUMEDREDGED = 0,
         DREDGINGPURPOSE = "None",
         DREDGE_TYPE = "None",
         LABOR_TYPE = LABOR_SOURCE,
         EXECYEAR = SURVEY_YEAR,
         FEATURENAME = SDSFEATURENAME,
         DATE_START = as.character(DATE_START),
         DATE_START = as_date(DATE_START)
         )|>
  select(SURVEYJOBIDPK,EXECYEAR,DATE_START,DREDGINGPURPOSE,VOLUMEDREDGED, RIVER,POOL, DREDGE_TYPE,UP_RIV_MIL,DN_RIV_MIL)



dredge_data_cleaning <- dredge_data |>
   filter(
          DREDGINGPURPOSE != "harbor",
           EXECYEAR <= 2022)|>
  mutate(
    river_code = str_sub(PREHYDROSURVEY_ID, 1, 2),
    pool_code = str_sub(PREHYDROSURVEY_ID, 4, 5),
    district_code = str_sub(PREHYDROSURVEY_ID, 7, 9),
    river_mile = str_sub(PREHYDROSURVEY_ID, 23, 30),
    year_iteration = str_sub(PREHYDROSURVEY_ID, 32,34),
    SURVEYJOBIDPK = ifelse(
      str_detect(PREHYDROSURVEY_ID, "MVRUM|MVRIW"),
      PREHYDROSURVEY_ID,
      paste0(district_code, river_code, pool_code, "_", river_mile, "_", year_iteration)  
    ),
      SURVEYJOBIDPK = str_replace_all(SURVEYJOBIDPK, "IL", "IW"),
     DATE_START = as_date(mdy_hm(DATE_START)),
    SDSFEATURENAME = FEATURENAME)|>
  select(SURVEYJOBIDPK,EXECYEAR,DREDGINGPURPOSE, VOLUMEDREDGED, RIVER,POOL, DREDGE_TYPE,DATE_START, UP_RIV_MIL,DN_RIV_MIL)



combined_data <- bind_rows(survey_Data, dredge_data_cleaning)

combined_data <-combined_data |>
     filter(DATE_START >= as.Date("1999-04-01") &
         DATE_START <= as.Date("2021-09-30"))


combined_data <-combined_data |>
  mutate(lead_7 = (DATE_START - 7),
         lead_14 = (DATE_START - 14))
Nas<- combined_data|>
  filter(if_any(everything(),is.na))

gage_survey <- combined_data |>
  left_join(gage_data2, by = "DATE_START")


na<-gage_survey |>
  select(everything()) |>
  summarise_all(list(~sum(is.na(.))))
na

NA_by_row<- gage_survey |>
  is.na() |>
  rowSums()

gf_histogram(~NA_by_row)


gage_survey_filt <- gage_survey |>
  filter(complete.cases(gage_survey))



gage_survey_full <- gage_survey_filt|>  
  left_join(gage_data2, by = c("lead_7" = "DATE_START"), suffix = c("", "_7"))|>
  left_join(gage_data2, by = c("lead_14" = "DATE_START"), suffix = c("","_14"))

Nas<- gage_survey_full|>
  select(-lead_7,-lead_14)|>
  filter(if_any(everything(),is.na))

gage_survey_cleaned <- gage_survey_full |>
  filter(complete.cases(gage_survey_full))

final_na<-gage_survey_cleaned|>
 select(-lead_7,-lead_14)|>
  filter(if_any(everything(),is.na))

### Create factored season variable that could be used in analysis
date_to_season <- function(date) {
  month <- as.numeric(format(date, "%m"))
  day <- as.numeric(format(date, "%d"))
  # Define the seasons based on date ranges
  if ((month == 3 && day >= 20) || (month >= 4 && month <= 6) || (month == 6 && day <= 20)) {
    return("Spring")
  } else if ((month == 6 && day >= 21) || (month >= 7 && month <= 9) || (month == 9 && day <= 21)) {
    return("Summer")
  } else if ((month == 9 && day >= 22) || (month >= 10 && month <= 12) || (month == 12 && day <= 20)) {
    return("Fall")
  } else {
    return("Winter")
  }
}

gage_survey_cleaned <- gage_survey_cleaned |>
  mutate("Season" = sapply(DATE_START,date_to_season))



```


```{r}
gage_survey_PCA <- gage_survey_cleaned |>
select(where(is.numeric), -EXECYEAR)

dredge_numeric<-gage_survey_cleaned|>
   select(where(is.numeric), -EXECYEAR)
correlations <-cor(dredge_numeric, use = "pairwise.complete.obs")
corrplot::corrplot(correlations)

dredge_prcomp <- gage_survey_PCA|>
  select(-VOLUMEDREDGED)

dredge_PCA = prcomp(dredge_prcomp, scale = T)

biplot(dredge_PCA)

plot(dredge_PCA,  type="l")

autoplot(dredge_PCA)


variable_contributions<- dredge_PCA$rotation
head(variable_contributions)

set.seed(12)
ctrl = trainControl(method = "cv", number = 5)

fit_pca = train(VOLUMEDREDGED ~ .,
            data = gage_survey_PCA,
            method = "glm",
            preProc = c("pca"),
            trControl = ctrl)
fit_pca

summary(fit_pca$finalModel)
varImp(fit_pca)
variable_contributions = fit_pca$preProcess$rotation
head(variable_contributions)

# data.frame(variable_contributions) |>
#   mutate(RIVER = gage_survey_cleaned$RIVER)
#   gf_point(PC2 ~ PC1)
 
data.frame(variable_contributions) |>
  gf_text(PC2 ~ PC1,
          label = row.names(variable_contributions))

data.frame(variable_contributions) |>
  filter(abs(PC1) > 0.11)

predictor_matrix <- gage_survey_PCA |>
  dplyr::select(-VOLUMEDREDGED) |> # Remove the response variable
  as.matrix() |>
  scale() #centers and scales



# The symbol %*% does matrix multiplication
data_in_PC_space = predictor_matrix %*% variable_contributions

data_in_PC_space = data.frame(data_in_PC_space,
                              River = gage_survey_cleaned$RIVER,
                              Pool = gage_survey_cleaned$POOL,
                              DREDGE_TYPE = gage_survey_cleaned$DREDGINGPURPOSE,
                              Season = gage_survey_cleaned$Season)

data.frame(data_in_PC_space)|>
  gf_point(PC2 ~ PC1, col = ~ Season)

data.frame(data_in_PC_space)|>
  gf_point(PC2 ~ PC1, col = ~DREDGE_TYPE)


### Scree Plot
data_in_PC_space = predictor_matrix %*% variable_contributions
var_explained = apply(data_in_PC_space,2,var)
pve = var_explained/sum(var_explained)
pve

cumsum(pve)

var_df <- data.frame(pve, PC = 1:length(pve),
                     cum_var = cumsum(pve))

var_df|>
  gf_point(cum_var ~ PC) |>
  gf_line(cum_var ~ PC)

pca_scores <-dredge_PCA$x
pca_loadings <- dredge_PCA$rotation






```

###xgBoost
```{r}
library(xgboost)
gage_xgb <- gage_survey_cleaned |>
  select(-lead_7, -lead_14,-DATE_START,
         -SURVEYJOBIDPK,-EXECYEAR,-DREDGE_TYPE,
         -DREDGINGPURPOSE)|>
    mutate_if(is.character, factor)
 
ctrl = trainControl(method = "cv", number = 10) 
fit_dredge = train(VOLUMEDREDGED ~ .,
                 data = gage_xgb,
                 method = "xgbTree",
               tuneGrid = expand.grid(nrounds = c (15,25,50,100), 
                                              max_depth = 1:10,
                                        eta =c(0.3), gamma = 0,
                                        colsample_bytree = 1,
                                        min_child_weight = 1, subsample = 1),
                 verbosity = 0,
                 trControl = ctrl,
                 na.action = na.exclude)

varImp(fit_dredge)
xgb.plot.tree(model = fit_dredge$finalModel, trees = 0)

fit_dredge

import_matrix = xgb.importance(model = fit_dredge$finalModel)
import_matrix
xgb.plot.importance(import_matrix)
```
###Cross Validation of Model
```{r}
set.seed(123)
n = nrow(gage_xgb)
n_outer_folds = 10

cv_pred = vector(length = n)

groups = rep(1:n_outer_folds, length = n)
cv_groups = sample(groups, n)


for(ii in 1:n_outer_folds){
  in_test = (cv_groups == ii)
  in_train = (cv_groups != ii)
 
 
  ctrl = trainControl(method = "cv", number = 10)
  fit_dredge_DCV = train(VOLUMEDREDGED ~ .,
                       data = gage_xgb[in_train, ],
                       method = "xgbTree",
                       tuneGrid = expand.grid(nrounds = c (15,25,50,100), 
                                              max_depth = 1:10,
                                        eta =c(0.3), gamma = 0,
                                        colsample_bytree = 1,
                                        min_child_weight = 1, subsample = 1),
                       verbosity = 0,
                       trControl = ctrl,
                       na.action = na.exclude)
 
  # "Frankenstein" vector of predictions
  cv_pred[in_test] = predict(fit_dredge_DCV,
                             newdata = gage_xgb[in_test, ])
 
}


##Og
train<-gage_xgb[in_train, ]
best_tune<-fit_dredge_DCV$results
best_tune
confusion_matrix <- confusionMatrix(cv_pred[in_test], gage_xgb[in_test, ])
print(confusion_matrix)

# I'll use RMSE to assess the model, because that's the metric I used to select the model.
# The model with the best RMSE may or may not be the one with the best MAE.
# RMSE
sqrt(mean((cv_pred - gage_xgb$VOLUMEDREDGED)^2)) # This is the most honest
                                         # assessment of accuracy
```

## Well that didnt work! Lets try modeling between the two river systems 
```{r}
combined_data <- bind_rows(survey_Data, dredge_data_cleaning)

combined_data <-combined_data |>
     filter(DATE_START >= as.Date("1999-04-01") &
         DATE_START <= as.Date("2021-09-30"))

combined_data <-combined_data |>
  mutate(lead_7 = (DATE_START - 7),
         lead_14 = (DATE_START - 14))
Nas<- combined_data|>
  filter(if_any(everything(),is.na))

gage_survey <- combined_data |>
  left_join(gage_data2, by = "DATE_START")

Illinois_River <- gage_survey |>
  select(SURVEYJOBIDPK,EXECYEAR,DATE_START,DREDGINGPURPOSE,VOLUMEDREDGED,RIVER,
         POOL, DREDGE_TYPE,UP_RIV_MIL, DN_RIV_MIL,lead_7,lead_14,BEAI2,HAVI2,
         HNYI2,IL03, IL03_Tail, IL04, IL04_Tail, IL05, IL05_Tail,IL06, IL06_Tail,
         IL07, IL07_Tail, IL08, IL08_Tail,KNGI2, MORI2, PIAI2) |>
  filter(RIVER == "Illinois_Waterway")
         

Miss_River <- gage_survey |>
  select(SURVEYJOBIDPK,EXECYEAR,DATE_START,DREDGINGPURPOSE,VOLUMEDREDGED,RIVER,
         POOL, DREDGE_TYPE,UP_RIV_MIL, DN_RIV_MIL,lead_7,lead_14,BRLI4,CMMI4, DBQI4,
         FAII4, KHBI2,MI11,MI11_Tail,MI12,MI12_Tail,MI13,MI13_Tail,MI14,MI14_Tail,
         MI15,MI15_Tail,MI16,MI16_Tail,MI17,MI17_Tail,MI18,MI18_Tail,MI19,MI19_Tail,
         MI20,MI20_Tail,MI21,MI21_Tail,MI22,MI22_Tail, MUSI4,UINI2) |>
  filter(RIVER == "Mississippi_River")

Miss_full <- Miss_River|>  
  left_join(gage_data2, by = c("lead_7" = "DATE_START"), suffix = c("", "_7"))|>
  left_join(gage_data2, by = c("lead_14" = "DATE_START"), suffix = c("","_14"))

IWW_full <- Illinois_River|>  
  left_join(gage_data2, by = c("lead_7" = "DATE_START"), suffix = c("", "_7"))|>
  left_join(gage_data2, by = c("lead_14" = "DATE_START"), suffix = c("","_14"))


Miss_Cleaned <- Miss_full |>
  filter(complete.cases(Miss_full))

IWW_Cleaned <- IWW_full |>
  filter(complete.cases(IWW_full))

IWW_Cleaned <- IWW_Cleaned |>
  mutate("Season" = sapply(DATE_START,date_to_season))


Miss_Cleaned <- Miss_Cleaned |>
  mutate("Season" = sapply(DATE_START,date_to_season))

```


## xgboost split by river
#Miss
```{r}
Miss_xgb <-Miss_Cleaned |>
  select(-lead_7, -lead_14,-DATE_START,
         -SURVEYJOBIDPK,-EXECYEAR,-DREDGE_TYPE,
         -DREDGINGPURPOSE, -RIVER)|>
    mutate_if(is.character, factor)
 
ctrl = trainControl(method = "cv", number = 10) 
Miss_xgb_fit = train(VOLUMEDREDGED ~ .,
                 data = Miss_xgb,
                 method = "xgbTree",
               tuneGrid = expand.grid(nrounds = c(15,25,50,100), 
                                              max_depth = 1:10,
                                        eta =c(0.3), gamma = 0,
                                        colsample_bytree = 1,
                                        min_child_weight = 1, subsample = 1),
                 verbosity = 0,
                 trControl = ctrl,
                 na.action = na.exclude)

varImp(Miss_xgb_fit)
xgb.plot.tree(model = Miss_xgb_fit$finalModel, trees = 0)

Miss_xgb_fit

import_matrix = xgb.importance(model = Miss_xgb_fit$finalModel)
import_matrix
xgb.plot.importance(import_matrix)
```

#IWW
```{r}
IWW_xgb <-IWW_Cleaned |>
  select(-lead_7, -lead_14,-DATE_START,
         -SURVEYJOBIDPK,-EXECYEAR,-DREDGE_TYPE,
         -DREDGINGPURPOSE, -RIVER)|>
    mutate_if(is.character, factor)
 
ctrl = trainControl(method = "cv", number = 10) 
IWW_xgb_fit = train(VOLUMEDREDGED ~ .,
                 data = IWW_xgb,
                 method = "xgbTree",
               tuneGrid = expand.grid(nrounds = c(15,25,50,100), 
                                              max_depth = 1:10,
                                        eta =c(0.3), gamma = 0,
                                        colsample_bytree = 1,
                                        min_child_weight = 1, subsample = 1),
                 verbosity = 0,
                 trControl = ctrl,
                 na.action = na.exclude)

varImp(IWW_xgb_fit)
xgb.plot.tree(model = IWW_xgb_fit$finalModel, trees = 0)

IWW_xgb_fit

import_matrix = xgb.importance(model = IWW_xgb_fit$finalModel)
import_matrix
xgb.plot.importance(import_matrix)
```

